repos:
  - repo: local
    hooks:
      - id: sqlmesh-format
        name: SQLMesh Format
        entry: bash -c '.env/bin/sqlmesh format || exit 0'
        language: system
        stages: [pre-commit]

      - id: sqlmesh-plan
        name: SQLMesh Plan
        entry: |
          bash -c '
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$branch" = "main" ]; then
            .env/bin/sqlmesh plan || exit 1
          fi
          '
        language: system
        stages: [pre-commit]