repos:
  - repo: local
    hooks:
      - id: sqlmesh-format
        name: SQLMesh Format
        entry: bash -c '.venv/bin/sqlmesh format || exit 0'
        language: system
        stages: [pre-commit]