project: jaffle_shop

gateways:
  local:
    connection:
      type: duckdb
      database: warehouse.duckdb
      extensions:
        - parquet

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2018-01-01
