project: jaffle_shop

default_target_environment: dev

gateways:
  local:
    connection:
      type: duckdb
      database: warehouse.duckdb
      extensions:
        - parquet

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2018-01-01

model_naming:
  infer_names: true